<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
include_once('EnumBasic.php');
class EnumConflictType extends EnumBasic {
    const COLLAR_CLASSIC = 'COLLAR_CLASSIC';
    const COLLAR_CLUB = 'COLLAR_CLUB';
    const COLLAR_CUTAWAY = 'COLLAR_CUTAWAY';
    const COLLAR_MINI = 'COLLAR_MINI';
    const COLLAR_BUTTON_DOWN = 'COLLAR_BUTTON_DOWN';
    const COLLAR_HIDDEN_BUTTON_DOWN = 'COLLAR_HIDDEN_BUTTON_DOWN';
    const COLLAR_NERHU_MANDARIN = 'COLLAR_NERHU_MANDARIN';
    const COLLAR_SEMI_SPREAD = 'COLLAR_SEMI_SPREAD';
    const COLLAR_SPREAD = 'COLLAR_SPREAD';
    const COLLAR_TUXEDO = 'COLLAR_TUXEDO';

    const CUFF_ANGLED = 'CUFF_ANGLED';
    const CUFF_COCKTAIL = 'CUFF_CUFF_COCKTAILANGLED';
    const CUFF_FRENCH_ANGLED = 'CUFF_FRENCH_ANGLED';
    const CUFF_FRENCH_ROUNDED = 'CUFF_FRENCH_ROUNDED';
    const CUFF_FRENCH_SQUARED = 'CUFF_FRENCH_SQUARED';
    const CUFF_ROUNDED = 'CUFF_ROUNDED';
    const CUFF_SQUARED = 'CUFF_SQUARED';

    const POCKET_1_ANGLED = 'POCKET_1_ANGLED';
    const POCKET_1_POINTED = 'POCKET_1_POINTED';
    const POCKET_1_ROUNDED = 'POCKET_1_ROUNDED';
    const POCKET_1_SQUARED = 'POCKET_1_SQUARED';
    const POCKET_2_ANGLED = 'POCKET_2_ANGLED';
    const POCKET_2_POINTED = 'POCKET_2_POINTED';
    const POCKET_2_ROUNDED = 'POCKET_2_ROUNDED';
    const POCKET_2_SQUARED = 'POCKET_2_SQUARED';

    const BOTTOM_CURVE = 'BOTTOM_CURVE';
    const BOTTOM_FLAT = 'BOTTOM_FLAT';

    const PLACKET_STANDARD = 'PLACKET_STANDARD';
    const PLACKET_SEAMLESS = 'PLACKET_SEAMLESS';
    const PLACKET_CONCEALED = 'PLACKET_CONCEALED';
    const PLACKET_TUXEDO = 'PLACKET_TUXEDO';

    const PLEAT_PLAIN = 'PLEAT_PLAIN';
    const PLEAT_BOX = 'PLEAT_BOX';
    const PLEAT_SIDEN = 'PLEAT_SIDEN';

    const YOKE_PLAIN = 'YOKE_PLAIN';
    const YOKE_SPLIT = 'YOKE_SPLIT';
}
